# Base configs
baseurl: "http://flaviomartins.photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-148079628-1"

# UI configs
title: "Photography by Flavio Martins"
subtitle: "Trained Engineer. Photographer in training."
author: "Flavio Martins"
bio: "I am learning photography in Lisbon, Portugal."
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/flaviomartins/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://facebook.com/flaviomartins.photography"
  twitter: "https://twitter.com/flaviomartins"
  instagram: "https://instagram.com/flaviomartins.photography"
  linkedin: "https://linkedin.com/in/flaviomartins"
  github: "https://github.com/flaviomartins"
